name: rife_env 
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy>=1.16,<1.24
  - tqdm>=4.35.0
  - sk-video>=1.1.10
  - pytorch>=1.6.0
  - opencv
  - moviepy>=1.0.3
  - torchvision>=0.7.0
  - pip
